### ISSUE TITLE
Branches in Github after PRs

### ISSUE THREAD

**Issue by alce65** [RafGarLo/202210-w3-wknd-rafael-garcia#7]
Hola Rafaél.
Veo que solo tienes  muchas ramas en Github ya mergeadas. Recuerda que hay que borrarlas al completar la PR. Sola la main y la feature/s en la que estemos trabajando deben estar en Github. Esta última se sube a remoto en cuanto tiene algún contenido. No hay que esperar a que este lista para la PR. De esta forma estamos salvaguardando nuestro trabajo en Github, por si acaso pasara algo en local.

**Comment by RafGarLo** [comment]
De acuerdo. Gracias. me pongo con ello.
